<?php

namespace Database\Seeders;

use App\Models\ProjectSetting;
use App\Models\Task;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database with complete timeline tasks.
     */
    public function run(): void
    {
        // Tanggal rujukan hari ini untuk outstanding tasks (dimulai hari ini, overdue = 0)
        $today = Carbon::today();

        // 1. Akun Admin Default
        User::updateOrCreate(
            ['username' => 'admin'],
            [
                'name' => 'Administrator ERP Odoo 18',
                'email' => 'admin@apotekkeluarga.com',
                'password' => Hash::make('admin123'),
            ]
        );

        // 2. Pengaturan Proyek & Password Akses Klien
        ProjectSetting::updateOrCreate(
            ['id' => 1],
            [
                'project_name' => 'Timeline Implementasi Odoo 18 Enterprise - PT. KSM & PT. SBK (Apotek Keluarga)',
                'client_password' => 'keluarga2026',
                'project_description' => 'Sistem pemantauan timeline terpadu implementasi Odoo 18 Enterprise pada Pedagang Besar Farmasi PT. Keluarga Sukses Mulia (KSM) dan 30 Outlet Retail Apotek Keluarga (PT. Sukses Bersama Keluarga / SBK).',
                'start_date' => '2026-01-01',
                'target_completion_date' => $today->copy()->addDays(60)->toDateString(),
                'client_contact_person' => 'Direksi PT. KSM & PT. SBK (Apotek Keluarga)',
                'version_tag' => 'Odoo 18 Enterprise - 30 Outlets Live',
            ]
        );

        // 3. Bersihkan Task Lama
        Task::truncate();

        // 4. Task List Lengkap Terpadu Sesuai Timeline Gambar
        $tasks = [

            // =========================================================================
            // FASE 1: PLANNING & SETUP WORKSPACE (01 JAN - 14 JAN 2026)
            // =========================================================================
            [
                'title' => 'Kick-off Meeting & Alignment Alur Bisnis KSM-SBK',
                'description' => 'Penyusunan dokumen Blueprint proses bisnis farmasi, penentuan ruang lingkup integrasi multi-company antara PBF KSM dan 30 outlet ritel Apotek Keluarga.',
                'module' => 'Planning & Workspace',
                'milestone' => 'Fase 1: Planning & Setup Workspace',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'Project Manager',
                'progress_percent' => 100,
                'start_date' => '2026-01-01',
                'due_date' => '2026-01-07',
                'completed_at' => '2026-01-07 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Setup Server Staging & Production Odoo 18',
                'description' => 'Provisioning Cloud Server, instalasi engine Odoo 18 Enterprise, PostgreSQL tuning, domain pointing, SSL security, dan setup repository Git.',
                'module' => 'Planning & Workspace',
                'milestone' => 'Fase 1: Planning & Setup Workspace',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'DevOps Engineer',
                'progress_percent' => 100,
                'start_date' => '2026-01-08',
                'due_date' => '2026-01-14',
                'completed_at' => '2026-01-14 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Multi-Company Structure Setup (PT KSM & PT SBK)',
                'description' => 'Konfigurasi arsitektur multi-company Odoo 18 untuk PT. Keluarga Sukses Mulia (PBF) dan PT. Sukses Bersama Keluarga (Retail 30 Outlet), setup hak akses dan security rules.',
                'module' => 'Planning & Workspace',
                'milestone' => 'Fase 1: Planning & Setup Workspace',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'ERP Consultant',
                'progress_percent' => 100,
                'start_date' => '2026-01-10',
                'due_date' => '2026-01-14',
                'completed_at' => '2026-01-14 18:00:00',
                'blocker_notes' => null,
            ],

            // =========================================================================
            // FASE 2: MASTER DATA & SUPPLY CHAIN (15 JAN - 05 FEB 2026)
            // =========================================================================
            [
                'title' => 'Master Data Obat, Alkes & Partner Principal',
                'description' => 'Migrasi dan standardisasi data master obat (kategori bebas, terbatas, keras, narkotika), SKU barcode pabrikan, principal supplier, dan lead time.',
                'module' => 'Inventory',
                'milestone' => 'Fase 2: Master Data & Supply Chain',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'Master Data Specialist',
                'progress_percent' => 100,
                'start_date' => '2026-01-15',
                'due_date' => '2026-01-22',
                'completed_at' => '2026-01-22 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Inventory Core & Multi Warehouse Gudang Pusat-Cabang',
                'description' => 'Konfigurasi gudang multi-lokasi untuk Gudang Pusat KSM (Transit, Quarantine, Good Stock) dan 30 lokasi gudang cabang retail SBK.',
                'module' => 'Inventory',
                'milestone' => 'Fase 2: Master Data & Supply Chain',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'Supply Chain Lead',
                'progress_percent' => 100,
                'start_date' => '2026-01-18',
                'due_date' => '2026-01-25',
                'completed_at' => '2026-01-25 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Stock Move Operation (Internal, Delivery, Receipt)',
                'description' => 'Standardisasi alur penerimaan barang dari principal, pengiriman ke outlet, dan pemindahan internal antar lokasi rak penyimpanan.',
                'module' => 'Inventory',
                'milestone' => 'Fase 2: Master Data & Supply Chain',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Warehouse Supervisor',
                'progress_percent' => 100,
                'start_date' => '2026-01-20',
                'due_date' => '2026-01-26',
                'completed_at' => '2026-01-26 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Auto Replenishment & Min-Max Reorder Point Farmasi',
                'description' => 'Konfigurasi otomatisasi reorder rule berdasarkan safety stock buffer dan rata-rata konsumsi obat per minggu untuk mencegah stock-out.',
                'module' => 'Inventory',
                'milestone' => 'Fase 2: Master Data & Supply Chain',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Inventory Analyst',
                'progress_percent' => 100,
                'start_date' => '2026-01-22',
                'due_date' => '2026-01-28',
                'completed_at' => '2026-01-28 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Alur Purchasing PBF: RFQ Hingga PO Validated',
                'description' => 'Standardisasi alur Request for Quotation (RFQ) ke distributor farmasi principal hingga terbit Purchase Order resmi bertanda tangan digital.',
                'module' => 'Purchasing',
                'milestone' => 'Fase 2: Master Data & Supply Chain',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'Purchasing Lead',
                'progress_percent' => 100,
                'start_date' => '2026-01-20',
                'due_date' => '2026-01-27',
                'completed_at' => '2026-01-27 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Fitur Close PO Otomatis & Toleransi Penerimaan',
                'description' => 'Otomatisasi penutupan status Purchase Order jika barang telah diterima sesuai batas toleransi kuantitas dari principal.',
                'module' => 'Purchasing',
                'milestone' => 'Fase 2: Master Data & Supply Chain',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Procurement Officer',
                'progress_percent' => 100,
                'start_date' => '2026-01-25',
                'due_date' => '2026-01-31',
                'completed_at' => '2026-01-31 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Fitur Retur Barang Supplier (Principal) & Outlet',
                'description' => 'Pengelolaan alur return merchandise authorization (RMA) untuk obat rusak, recall pabrik, atau menjelang tanggal kadaluarsa (ED).',
                'module' => 'Inventory',
                'milestone' => 'Fase 2: Master Data & Supply Chain',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'QA Farmasi',
                'progress_percent' => 100,
                'start_date' => '2026-01-26',
                'due_date' => '2026-02-02',
                'completed_at' => '2026-02-02 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Inter-Company Transaction (Mutasi KSM - SBK Outlet)',
                'description' => 'Otomatisasi transaksi jual-beli internal: SO otomatis terbuat di PT KSM saat Outlet SBK membuat PO permintaan dropping stok obat.',
                'module' => 'Purchasing',
                'milestone' => 'Fase 2: Master Data & Supply Chain',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'Solution Architect',
                'progress_percent' => 100,
                'start_date' => '2026-01-25',
                'due_date' => '2026-02-03',
                'completed_at' => '2026-02-03 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Aplikasi Stock Opname Barcode Scanner & Selisih Fisik',
                'description' => 'Aplikasi mobile/barcode reader untuk stock opname berkala outlet dengan pencatatan selisih fisik dan penyesuaian inventory adjustment otomatis.',
                'module' => 'Inventory',
                'milestone' => 'Fase 2: Master Data & Supply Chain',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Mobile Dev & QA',
                'progress_percent' => 100,
                'start_date' => '2026-01-28',
                'due_date' => '2026-02-05',
                'completed_at' => '2026-02-05 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Analisis Pareto ABC & Laporan Stock Aging Obat Kadaluarsa',
                'description' => 'Laporan klasifikasi obat kategori Fast Moving vs Slow Moving (Pareto 80/20) dan monitoring umur simpan batch obat (FEFO).',
                'module' => 'Inventory',
                'milestone' => 'Fase 2: Master Data & Supply Chain',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Data Analyst',
                'progress_percent' => 100,
                'start_date' => '2026-01-28',
                'due_date' => '2026-02-05',
                'completed_at' => '2026-02-05 18:00:00',
                'blocker_notes' => null,
            ],

            // =========================================================================
            // FASE 3: SALES, POS & MULTI-UOM (01 FEB - 15 FEB 2026)
            // =========================================================================
            [
                'title' => 'Alur Sales Quotation hingga Sales Order (SO)',
                'description' => 'Pembuatan quotation penjualan grosir PBF KSM, konfirmasi SO, approval diskon, auto refresh status SO, dan auto close SO > 60 hari.',
                'module' => 'Sales',
                'milestone' => 'Fase 3: Sales, POS & Multi-UoM',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Sales Lead KSM',
                'progress_percent' => 100,
                'start_date' => '2026-02-01',
                'due_date' => '2026-02-07',
                'completed_at' => '2026-02-07 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Custom Multi UoM Pricelist (Box / Strip / Tablet)',
                'description' => 'Konversi satuan farmasi multi-level (Box, Strip, Tablet, Botol) dengan sistem harga otomatis sesuai satuan kemasan obat yang dibeli konsumen.',
                'module' => 'Sales',
                'milestone' => 'Fase 3: Sales, POS & Multi-UoM',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'Developer Odoo',
                'progress_percent' => 100,
                'start_date' => '2026-02-03',
                'due_date' => '2026-02-10',
                'completed_at' => '2026-02-10 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Setup Point of Sale (POS) Kasir Retail Apotek',
                'description' => 'Konfigurasi modul kasir Odoo 18 untuk layar kasir cepat, barcode scanner USB/Bluetooth, struk thermal, cash drawer, dan multi-payment.',
                'module' => 'POS',
                'milestone' => 'Fase 3: Sales, POS & Multi-UoM',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'POS Specialist',
                'progress_percent' => 100,
                'start_date' => '2026-02-05',
                'due_date' => '2026-02-14',
                'completed_at' => '2026-02-14 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Fitur Lost Sales Analysis POS',
                'description' => 'Pencatatan obat yang dicari pelanggan namun tidak tersedia di stok cabang untuk dianalisis oleh tim pengadaan.',
                'module' => 'POS',
                'milestone' => 'Fase 3: Sales, POS & Multi-UoM',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Business Analyst',
                'progress_percent' => 100,
                'start_date' => '2026-02-08',
                'due_date' => '2026-02-14',
                'completed_at' => '2026-02-14 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Fitur Salesperson & Apoteker Commission',
                'description' => 'Perhitungan komisi dan poin penjualan obat OTC atau racikan resep untuk kasir, TTK, dan Apoteker Penanggung Jawab.',
                'module' => 'POS',
                'milestone' => 'Fase 3: Sales, POS & Multi-UoM',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Finance & HR',
                'progress_percent' => 100,
                'start_date' => '2026-02-10',
                'due_date' => '2026-02-15',
                'completed_at' => '2026-02-15 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Custom Multi UoM Kasir dan Multi Pricelist Member',
                'description' => 'Dukungan kasir memilih satuan eceran (Strip/Tablet) secara langsung di antarmuka POS dengan harga khusus member/loyalty.',
                'module' => 'POS',
                'milestone' => 'Fase 3: Sales, POS & Multi-UoM',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Developer Odoo',
                'progress_percent' => 100,
                'start_date' => '2026-02-11',
                'due_date' => '2026-02-15',
                'completed_at' => '2026-02-15 18:00:00',
                'blocker_notes' => null,
            ],

            // =========================================================================
            // FASE 4: ROLLOUT 30 OUTLET (100% LIVE) - APOTEK KELUARGA 01 s/d 31 (TANPA 10)
            // =========================================================================

            [
                'title' => 'Rollout Outlet Apotek Keluarga 01',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 01.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'Tim Deployment Wave 1',
                'progress_percent' => 100,
                'start_date' => '2026-02-01',
                'due_date' => '2026-02-05',
                'completed_at' => '2026-02-05 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 02',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 02.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'Tim Deployment Wave 1',
                'progress_percent' => 100,
                'start_date' => '2026-02-02',
                'due_date' => '2026-02-06',
                'completed_at' => '2026-02-06 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 03',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 03.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'Tim Deployment Wave 1',
                'progress_percent' => 100,
                'start_date' => '2026-02-03',
                'due_date' => '2026-02-08',
                'completed_at' => '2026-02-08 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 04',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 04.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'Tim Deployment Wave 1',
                'progress_percent' => 100,
                'start_date' => '2026-02-05',
                'due_date' => '2026-02-09',
                'completed_at' => '2026-02-09 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 05',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 05.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'urgent',
                'pic_name' => 'Tim Deployment Wave 1',
                'progress_percent' => 100,
                'start_date' => '2026-02-06',
                'due_date' => '2026-02-10',
                'completed_at' => '2026-02-10 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 06',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 06.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 2',
                'progress_percent' => 100,
                'start_date' => '2026-02-11',
                'due_date' => '2026-02-15',
                'completed_at' => '2026-02-15 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 07',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 07.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 2',
                'progress_percent' => 100,
                'start_date' => '2026-02-12',
                'due_date' => '2026-02-16',
                'completed_at' => '2026-02-16 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 08',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 08.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 2',
                'progress_percent' => 100,
                'start_date' => '2026-02-13',
                'due_date' => '2026-02-17',
                'completed_at' => '2026-02-17 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 09',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 09.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 2',
                'progress_percent' => 100,
                'start_date' => '2026-02-14',
                'due_date' => '2026-02-18',
                'completed_at' => '2026-02-18 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 11',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 11.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 2',
                'progress_percent' => 100,
                'start_date' => '2026-02-15',
                'due_date' => '2026-02-19',
                'completed_at' => '2026-02-19 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 12',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 12.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 2',
                'progress_percent' => 100,
                'start_date' => '2026-02-16',
                'due_date' => '2026-02-20',
                'completed_at' => '2026-02-20 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 13',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 13.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 2',
                'progress_percent' => 100,
                'start_date' => '2026-02-16',
                'due_date' => '2026-02-20',
                'completed_at' => '2026-02-20 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 14',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 14.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 3',
                'progress_percent' => 100,
                'start_date' => '2026-02-21',
                'due_date' => '2026-02-26',
                'completed_at' => '2026-02-26 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 15',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 15.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 3',
                'progress_percent' => 100,
                'start_date' => '2026-02-22',
                'due_date' => '2026-02-27',
                'completed_at' => '2026-02-27 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 16',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 16.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 3',
                'progress_percent' => 100,
                'start_date' => '2026-02-23',
                'due_date' => '2026-02-28',
                'completed_at' => '2026-02-28 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 17',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 17.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 3',
                'progress_percent' => 100,
                'start_date' => '2026-02-25',
                'due_date' => '2026-03-01',
                'completed_at' => '2026-03-01 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 18',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 18.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 3',
                'progress_percent' => 100,
                'start_date' => '2026-02-26',
                'due_date' => '2026-03-02',
                'completed_at' => '2026-03-02 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 19',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 19.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 3',
                'progress_percent' => 100,
                'start_date' => '2026-02-27',
                'due_date' => '2026-03-03',
                'completed_at' => '2026-03-03 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 20',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 20.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 3',
                'progress_percent' => 100,
                'start_date' => '2026-02-28',
                'due_date' => '2026-03-04',
                'completed_at' => '2026-03-04 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 21',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 21.',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Tim Deployment Wave 3',
                'progress_percent' => 100,
                'start_date' => '2026-03-01',
                'due_date' => '2026-03-05',
                'completed_at' => '2026-03-05 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 22',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 22 (Penuntasan 30 Outlet Live).',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Tim Deployment Wave 4',
                'progress_percent' => 100,
                'start_date' => '2026-03-06',
                'due_date' => '2026-03-12',
                'completed_at' => '2026-03-12 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 23',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 23 (Penuntasan 30 Outlet Live).',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Tim Deployment Wave 4',
                'progress_percent' => 100,
                'start_date' => '2026-03-08',
                'due_date' => '2026-03-14',
                'completed_at' => '2026-03-14 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 24',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 24 (Penuntasan 30 Outlet Live).',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Tim Deployment Wave 4',
                'progress_percent' => 100,
                'start_date' => '2026-03-10',
                'due_date' => '2026-03-16',
                'completed_at' => '2026-03-16 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 25',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 25 (Penuntasan 30 Outlet Live).',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Tim Deployment Wave 4',
                'progress_percent' => 100,
                'start_date' => '2026-03-12',
                'due_date' => '2026-03-18',
                'completed_at' => '2026-03-18 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 26',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 26 (Penuntasan 30 Outlet Live).',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Tim Deployment Wave 4',
                'progress_percent' => 100,
                'start_date' => '2026-03-14',
                'due_date' => '2026-03-20',
                'completed_at' => '2026-03-20 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 27',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 27 (Penuntasan 30 Outlet Live).',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Tim Deployment Wave 4',
                'progress_percent' => 100,
                'start_date' => '2026-03-16',
                'due_date' => '2026-03-22',
                'completed_at' => '2026-03-22 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 28',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 28 (Penuntasan 30 Outlet Live).',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Tim Deployment Wave 4',
                'progress_percent' => 100,
                'start_date' => '2026-03-18',
                'due_date' => '2026-03-24',
                'completed_at' => '2026-03-24 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 29',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 29 (Penuntasan 30 Outlet Live).',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Tim Deployment Wave 4',
                'progress_percent' => 100,
                'start_date' => '2026-03-20',
                'due_date' => '2026-03-26',
                'completed_at' => '2026-03-26 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 30',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 30 (Penuntasan 30 Outlet Live).',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Tim Deployment Wave 4',
                'progress_percent' => 100,
                'start_date' => '2026-03-22',
                'due_date' => '2026-03-28',
                'completed_at' => '2026-03-28 16:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Rollout Outlet Apotek Keluarga 31',
                'description' => 'Go-live kasir POS Odoo 18, scanner barcode, cut-off sistem lama, migrasi saldo awal stok fisik, dan pelatihan staf kasir/apoteker cabang Apotek Keluarga 31 (Penuntasan 30 Outlet Live).',
                'module' => 'Rollout Outlet',
                'milestone' => 'Fase 4: Rollout 30 Outlet (100% Live)',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Tim Deployment Wave 4',
                'progress_percent' => 100,
                'start_date' => '2026-03-24',
                'due_date' => '2026-03-31',
                'completed_at' => '2026-03-31 17:00:00',
                'blocker_notes' => null,
            ],

            // =========================================================================
            // FASE 5: ACCOUNTING & FINANCIAL REFINEMENT (MULAI HARI INI - TARGET OKTOBER 2026)
            // =========================================================================
            [
                'title' => 'Penyusunan Format COA (Chart of Accounts) Apotek',
                'description' => 'Standardisasi bagan akun akuntansi konsolidasi multi-company antara PBF KSM dan Retail Apotek SBK.',
                'module' => 'Accounting',
                'milestone' => 'Fase 5: Accounting & Financial Refinement',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Indra Finance',
                'progress_percent' => 100,
                'start_date' => '2026-02-01',
                'due_date' => '2026-02-15',
                'completed_at' => '2026-02-15 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Penyusunan Format Journal Entries & Akun Penampung Kasir',
                'description' => 'Mapping akun penampung penerimaan kas/bank, selisih kas kasir, piutang debit/kredit EDC, dan diskon promosi outlet.',
                'module' => 'Accounting',
                'milestone' => 'Fase 5: Accounting & Financial Refinement',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Accounting Officer',
                'progress_percent' => 100,
                'start_date' => '2026-02-10',
                'due_date' => '2026-02-22',
                'completed_at' => '2026-02-22 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Fitur Bank Reconciliation Terpadu',
                'description' => 'Rekonsiliasi mutasi rekening koran bank dengan catatan buku kas perusahaan untuk mendeteksi transaksi tertunda.',
                'module' => 'Accounting',
                'milestone' => 'Fase 5: Accounting & Financial Refinement',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Finance Staff',
                'progress_percent' => 100,
                'start_date' => '2026-02-15',
                'due_date' => '2026-02-28',
                'completed_at' => '2026-02-28 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Auto Match EDC by RRN Number',
                'description' => 'Pencocokan otomatis transaksi kartu debit/kredit di POS dengan settlement bank merchant menggunakan nomor referensi RRN.',
                'module' => 'Accounting',
                'milestone' => 'Fase 5: Accounting & Financial Refinement',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Developer Odoo',
                'progress_percent' => 100,
                'start_date' => '2026-02-20',
                'due_date' => '2026-03-05',
                'completed_at' => '2026-03-05 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Auto Journal Posting to Accounting Engine',
                'description' => 'Posting jurnal otomatis dari setiap transaksi POS kasir dan penerimaan gudang langsung ke pembukuan besar (General Ledger).',
                'module' => 'Accounting',
                'milestone' => 'Fase 5: Accounting & Financial Refinement',
                'status' => 'review',
                'priority' => 'urgent',
                'pic_name' => 'Accounting Lead',
                'progress_percent' => 90,
                'start_date' => $today->copy()->toDateString(),
                'due_date' => $today->copy()->addDays(5)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => 'Menunggu verifikasi hasil audit balance posting harian kasir cabang.',
            ],
            [
                'title' => 'Integrasi Pajak e-Faktur & PPh 21/23 Farmasi',
                'description' => 'Konfigurasi pelaporan faktur pajak PPN keluaran atas penjualan grosir KSM dan pemotongan PPh jasa dokter apotek.',
                'module' => 'Accounting',
                'milestone' => 'Fase 5: Accounting & Financial Refinement',
                'status' => 'in_progress',
                'priority' => 'high',
                'pic_name' => 'Tax Consultant',
                'progress_percent' => 75,
                'start_date' => $today->copy()->toDateString(),
                'due_date' => $today->copy()->addDays(10)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => null,
            ],
            [
                'title' => 'Penetapan HPP Otomatis (COGS Calculation) Multi-Cabang',
                'description' => 'Perhitungan Harga Pokok Penjualan (HPP) otomatis per outlet dengan metode Average Costing / FIFO farmasi.',
                'module' => 'Accounting',
                'milestone' => 'Fase 5: Accounting & Financial Refinement',
                'status' => 'blocked',
                'priority' => 'urgent',
                'pic_name' => 'Accounting Consultant',
                'progress_percent' => 40,
                'start_date' => $today->copy()->toDateString(),
                'due_date' => $today->copy()->addDays(15)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => 'Perbedaan harga perolehan batch expired date dan bonus prinsipal belum ter-reconcile sempurna.',
            ],
            [
                'title' => 'Valuasi Persediaan Realtime (AVCO Method)',
                'description' => 'Sinkronisasi nilai persediaan barang dagang di neraca dengan kartu stok fisik gudang secara realtime.',
                'module' => 'Accounting',
                'milestone' => 'Fase 5: Accounting & Financial Refinement',
                'status' => 'in_progress',
                'priority' => 'high',
                'pic_name' => 'Finance & Inventory',
                'progress_percent' => 60,
                'start_date' => $today->copy()->toDateString(),
                'due_date' => $today->copy()->addDays(20)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => null,
            ],
            [
                'title' => 'Sinkronisasi Laporan Keuangan Neraca & Laba Rugi Multi-Company',
                'description' => 'Konsolidasi laporan keuangan antara PBF KSM dan PT SBK dengan eliminasi transaksi antar-perusahaan otomatis.',
                'module' => 'Accounting',
                'milestone' => 'Fase 5: Accounting & Financial Refinement',
                'status' => 'blocked',
                'priority' => 'urgent',
                'pic_name' => 'Chief Financial Officer',
                'progress_percent' => 35,
                'start_date' => $today->copy()->toDateString(),
                'due_date' => $today->copy()->addDays(25)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => 'Alur jurnal inter-company COGS dan penyesuaian laba rugi konsolidasi masih memerlukan approval direksi.',
            ],

            // =========================================================================
            // FASE 6: HUMAN RESOURCES & GENERAL AFFAIR / HCGA (MULAI HARI INI - TARGET OKT/NOV 2026)
            // =========================================================================
            [
                'title' => 'Master Karyawan, Dokter Jaga & Tenaga Teknis Farmasi',
                'description' => 'Basis data SDM seluruh karyawan pusat, apoteker penanggung jawab (APJ), asisten apoteker (TTK), kasir, dan dokter jaga.',
                'module' => 'HR',
                'milestone' => 'Fase 6: HR & General Affair (HCGA)',
                'status' => 'in_progress',
                'priority' => 'medium',
                'pic_name' => 'HR Manager',
                'progress_percent' => 70,
                'start_date' => $today->copy()->toDateString(),
                'due_date' => $today->copy()->addDays(12)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => null,
            ],
            [
                'title' => 'Integrasi Mesin Absensi Fingerprint Outlet & Shift Kerja 24 Jam',
                'description' => 'Penjadwalan shift kerja berputar (Pagi, Siang, Malam/24 Jam) dan integrasi absensi biometrik online seluruh outlet.',
                'module' => 'HR',
                'milestone' => 'Fase 6: HR & General Affair (HCGA)',
                'status' => 'in_progress',
                'priority' => 'medium',
                'pic_name' => 'IT Support Outlet',
                'progress_percent' => 50,
                'start_date' => $today->copy()->toDateString(),
                'due_date' => $today->copy()->addDays(17)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => null,
            ],
            [
                'title' => 'Payroll & Slip Gaji Karyawan Multi-Outlet Terintegrasi',
                'description' => 'Perhitungan gaji pokok, tunjangan keahlian kefarmasian, uang makan, lembur, dan potongan otomatis langsung ke slip gaji digital.',
                'module' => 'HR',
                'milestone' => 'Fase 6: HR & General Affair (HCGA)',
                'status' => 'in_progress',
                'priority' => 'high',
                'pic_name' => 'Payroll Specialist',
                'progress_percent' => 40,
                'start_date' => $today->copy()->toDateString(),
                'due_date' => $today->copy()->addDays(25)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => null,
            ],
            [
                'title' => 'Klaim BPJS Ketenagakerjaan & Kesehatan Karyawan',
                'description' => 'Otomatisasi kalkulasi iuran BPJS Kesehatan dan BPJS Ketenagakerjaan (JKK, JKM, JHT, JP) pada slip gaji bulanan.',
                'module' => 'HR',
                'milestone' => 'Fase 6: HR & General Affair (HCGA)',
                'status' => 'backlog',
                'priority' => 'low',
                'pic_name' => 'HR Officer',
                'progress_percent' => 0,
                'start_date' => $today->copy()->addDays(6)->toDateString(),
                'due_date' => $today->copy()->addDays(35)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => null,
            ],
            [
                'title' => 'Manajemen Cuti & Izin Sakit Karyawan Online',
                'description' => 'Pengajuan cuti tahunan, cuti melahirkan, dan izin sakit berbasis portal self-service karyawan dengan alur persetujuan atasan.',
                'module' => 'HR',
                'milestone' => 'Fase 6: HR & General Affair (HCGA)',
                'status' => 'backlog',
                'priority' => 'low',
                'pic_name' => 'HR Specialist',
                'progress_percent' => 0,
                'start_date' => $today->copy()->addDays(10)->toDateString(),
                'due_date' => $today->copy()->addDays(40)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => null,
            ],
            [
                'title' => 'HCGA: Asset Tracking & Perawatan Alat Kesehatan/Kulkas Obat',
                'description' => 'Pencatatan nomor seri aset cabang (kulkas vaccine chiller, genset, AC ruangan obat) dan jadwal pemeliharaan berkala.',
                'module' => 'HCGA',
                'milestone' => 'Fase 6: HR & General Affair (HCGA)',
                'status' => 'backlog',
                'priority' => 'medium',
                'pic_name' => 'GA Officer',
                'progress_percent' => 0,
                'start_date' => $today->copy()->addDays(12)->toDateString(),
                'due_date' => $today->copy()->addDays(45)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => null,
            ],
            [
                'title' => 'Pengelolaan Surat Izin Praktik Apoteker (SIPA) & Kepatuhan Legal',
                'description' => 'Sistem pengingat masa berlaku SIPA apoteker dan izin operasional klinik/apotek sebelum batas kadaluarsa.',
                'module' => 'HCGA',
                'milestone' => 'Fase 6: HR & General Affair (HCGA)',
                'status' => 'backlog',
                'priority' => 'high',
                'pic_name' => 'Legal & Compliance',
                'progress_percent' => 0,
                'start_date' => $today->copy()->addDays(15)->toDateString(),
                'due_date' => $today->copy()->addDays(50)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => null,
            ],
            [
                'title' => 'General Affair: Procurement ATK & Logistik Non-Medis Cabang',
                'description' => 'Standardisasi pengajuan kebutuhan operasional non-medis cabang (kertas struk thermal, kantong plastik apotek, perlengkapan sanitasi).',
                'module' => 'HCGA',
                'milestone' => 'Fase 6: HR & General Affair (HCGA)',
                'status' => 'backlog',
                'priority' => 'medium',
                'pic_name' => 'HR Manager',
                'progress_percent' => 0,
                'start_date' => $today->copy()->addDays(17)->toDateString(),
                'due_date' => $today->copy()->addDays(55)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => null,
            ],

            // =========================================================================
            // FASE 7: DIGITAL EXPANSION & AI INTELLIGENCE (01 MAR s/d OKTOBER 2026)
            // =========================================================================
            [
                'title' => 'Website Profil Perusahaan & Katalog Online',
                'description' => 'Portal web resmi Apotek Keluarga berisi profil 30 cabang, jam buka, layanan apotek 24 jam, dan katalog produk farmasi OTC.',
                'module' => 'Website & Customer',
                'milestone' => 'Fase 7: Digital Expansion & AI',
                'status' => 'completed',
                'priority' => 'medium',
                'pic_name' => 'Web Developer',
                'progress_percent' => 100,
                'start_date' => '2026-03-01',
                'due_date' => '2026-03-15',
                'completed_at' => '2026-03-15 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Internal AI Assistant untuk Farmasi & SOP',
                'description' => 'Asisten cerdas berbasis AI untuk apoteker dan staf dalam mencari informasi interaksi obat, dosis racikan, dan SOP penanganan resep.',
                'module' => 'Module AI',
                'milestone' => 'Fase 7: Digital Expansion & AI',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'AI Engineer',
                'progress_percent' => 100,
                'start_date' => '2026-03-10',
                'due_date' => '2026-03-25',
                'completed_at' => '2026-03-25 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'AI Customer Consumption Analysis & Reorder',
                'description' => 'Analitik AI terhadap kebiasaan pembelian obat rutin pasien kronis (Diabetes, Hipertensi) untuk pengingat jadwal tebus resep otomatis.',
                'module' => 'Module AI',
                'milestone' => 'Fase 7: Digital Expansion & AI',
                'status' => 'completed',
                'priority' => 'high',
                'pic_name' => 'Data Scientist',
                'progress_percent' => 100,
                'start_date' => '2026-03-15',
                'due_date' => '2026-03-31',
                'completed_at' => '2026-03-31 17:00:00',
                'blocker_notes' => null,
            ],
            [
                'title' => 'Customer Dashboard & Portal Riwayat Resep Pelanggan',
                'description' => 'Peningkatan dashboard membership bagi pelanggan untuk melihat riwayat pembelian obat, klaim poin loyalty, dan unggah resep dokter.',
                'module' => 'Website & Customer',
                'milestone' => 'Fase 7: Digital Expansion & AI',
                'status' => 'in_progress',
                'priority' => 'medium',
                'pic_name' => 'Frontend Developer',
                'progress_percent' => 50,
                'start_date' => $today->copy()->toDateString(),
                'due_date' => $today->copy()->addDays(20)->toDateString(),
                'completed_at' => null,
                'blocker_notes' => null,
            ],

        ];

        foreach ($tasks as $taskData) {
            Task::create($taskData);
        }
    }
}